esphome:
  friendly_name: "${friendly_name}"
  name: "${full_name}"
  area: "${area}"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "cportal-${name}"
    password: !secret cportal_password

captive_portal: