substitutions:
  type: sensor
  name: air
  area: bedroom
  full_name: "${area}-${name}-${type}"
  friendly_name: "Bedroom Air"

esp8266:
  board: esp07s

<<: !include base.yaml

i2c:
  sda: GPIO10
  scl: GPIO09
  scan: true
  id: i2c_a

uart:
  tx_pin: GPIO12
  rx_pin: GPIO14
  baud_rate: 9600
  id: uart_a

sensor:
  - platform: bme280_i2c
    i2c_id: i2c_a
    address: 0x76
    temperature:
      name: "${friendly_name} Temperature"
    pressure:
      name: "${friendly_name} Pressure"
    humidity:
      name: "${friendly_name} Humidity"
  - platform: adc
    pin: GPIO17
    name: "${friendly_name} VDD"
    update_interval: 60s 
  - platform: mhz19
    uart_id: uart_a
    co2:
      name: "${friendly_name} CO2"
    temperature:
      name: "${friendly_name} Temperature Inaccurate"
