substitutions:
  type: sensor
  name: jarvis
  area: bedroom
  full_name: "${area}-${name}-${type}"
  friendly_name: "Bedroom Jarvis Sensor"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: recommended

<<: !include base.yaml
<<: !include base.atom_satellite.yaml
