substitutions:
  type: lamp
  name: ledstrip
  area: bedroom
  full_name: "${area}-${name}-${type}"
  friendly_name: "Bedroom Ledstrip Lamp"

esp8266:
  board: esp01_1m

<<: !include base.yaml

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO0
    inverted: true
    frequency: 1000Hz

light:
  - platform: monochromatic
    name: "${friendly_name}"
    output: pwm_output
    id: pwm_light
    restore_mode: ALWAYS_ON
