substitutions:
  type: lamp
  name: ledbottles
  area: livingroom
  full_name: "${area}-${name}-${type}"
  friendly_name: "Livingroom Led Bottles Lamp"

esp8266:
  board: esp07s

<<: !include base.yaml

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO13
    frequency: 1000Hz

light:
  - platform: monochromatic
    name: "${friendly_name}"
    output: pwm_output
    id: pwm_light
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 2000ms
          update_interval: 2s
          min_brightness: 20%

