substitutions:
  type: lamp
  name: table
  area: livingroom
  full_name: "${area}-${name}-${type}"
  friendly_name: "Livingroom Table Lamp"

esp8266:
  board: esp01_1m

<<: !include base.yaml

output:
  - platform: gpio
    id: light_output
    pin: GPIO0

light:
  - platform: binary
    name: "${friendly_name}"
    output: light_output
    restore_mode: ALWAYS_ON
    effects:
      - strobe:
