substitutions:
  type: controller
  name: plant0
  area: livingroom
  full_name: "${area}-${name}-${type}"
  friendly_name: "Plant0 Controller"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

<<: !include base.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "cportal-${name}"
    password: !secret cportal_password

  output_power: 8.5dB

binary_sensor:
  - platform: gpio
    id: water_flow_sensor
    name: "${friendly_name} Water Flow Sensor"
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: true
    filters:
      - invert:

script:
  - id: enable_water_flow_5s
    then:
      - wait_until:
          condition:
            binary_sensor.is_on: water_flow_sensor
          timeout: 10s
      - if:
          condition:
            binary_sensor.is_on: water_flow_sensor
          then:
            - delay: 2s
            - switch.turn_off: water_pump
            - delay: 3s
            - switch.turn_on: water_pump
            - delay: 3s
      - switch.turn_off: water_pump

switch:
  - platform: gpio
    name: "${friendly_name} Water Pump"
    pin: GPIO0
    id: water_pump
    on_turn_on:
      - script.execute: enable_water_flow_5s
